apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: ingress-sc
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: ingress-sc
    app.kubernetes.io/part-of: insights-ingress-go
  name: ingress-sc
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app.kubernetes.io/instance: ingress-sc
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/instance: ingress-sc
    spec:
      containers:
      - image: image
        imagePullPolicy: Always
        name: container-image
        ports:
        - containerPort: 9000
        resources:
          requests:
            cpu: 10m
            memory: 256Mi
status: {}
